it_interview:
  name: ๐ฉ๐ผโ๐ป ะะพะนัะธ ัะพะฑะตัะตะดะพะฒะฐะฝะธะต ะฒ IT
  welcome_message: ๐ฉ๐ผโ๐ป ะะปะปะพัะฐ, ะะฐ ะฒัะต ะฒะพะฟัะพัั ะฒัะตะผั ะพะณัะฐะฝะธัะตะฝะฝะพ (ัะฒะธะดะตัั ัะฐะนะผะตั)! ะะพัะพะฒ? ะัะปะธ ะดะฐ, ะพัะฟัะฐะฒั ะปัะฑะพะต ัะพะพะฑัะตะฝะธะต
  parse_mode: markdown

code_assistant:
  name: ๐ฉ๐ผโ๐ป ะะพะผะพัั ะฒ ะบะพะดะต
  welcome_message: ๐ฉ๐ผโ๐ป ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: markdown

artist:
  name: ๐ฉโ๐จ ะขะฒะพะน ััะดะพะถะฝะธะบ
  welcome_message: ๐ฉโ๐จ ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?

startup_idea_generator:
  name: ๐ก ะัะธะดัะผะฐัั ะธะดะตั? ะะตะณะบะพ!
  welcome_message: ๐ก ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: html

text_improver:
  name: ๐ ะฅะพัะตัั ัะดะตะปะฐัั ัะตะบั ะปัััะต? ะะต ะฒะพะฟัะพั!
  welcome_message: ๐  ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: html

motivator:
  name: ๐ Motivator
  welcome_message: ๐ ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: html

sql_assistant:
  name: ๐ ะัะผะฐะตัั SQL ัะปะพะถะฝะพ? ะฏ ัะตะฑะต ะฟะพะผะพะณั
  welcome_message: ๐ ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: markdown

movie_expert:
  name: ๐ฌ ะฅะพัะตัั ัะบะพัะพัะฐัั ัะฐัะพะบ? ะะพะดะฑะตัั ัะธะปัะผ
  welcome_message: ๐ฌ ะะปะปะพัะฐ, ัะตะผ ะผะพะณั ัะตะฑะต ะฟะพะผะพัั?
  parse_mode: html
